generatorName: rust
library: reqwest
templateDir: "/local/templates/rust"
additionalProperties:
  supportAsync: true
  packageName: nomad-client
  packageVersion: 0.0.1
  packageDescription: "A Rust client for HashiCorp Nomad's API."
  packageHomepage: "https://github.com/rivet-gg/Nomad.OAS/tree/master/clients/rust"
  packageRepository: "https://github.com/rivet-gg/Nomad.OAS"
  packageKeywords: 
    - nomad
    - hashicorp
    - api
    - client
    - openapi
    - swagger
  packageCategories: 
    - api-bindings
  packageAuthors: 
    - "FuturistiCoder <FuturistiCoder@gmail.com>"
    - "Nathan Flurry <developer@nathanflurry.com>"
  packageLicense: "MIT"


# inputSpec: "/local/dist/swagger.json"
# output: "/local/clients/rust/"
